Feature/co 868 impl
osu-mist/positions-api pull request #2
Opened 2017-07-25 07:07 UTC by floppyears

2017-07-25 21:36 UTC, gmtcrary requested changes

2017-07-25 21:36 UTC, adpextwindong commented on src/main/groovy/edu/oregonstate/mist/positions/resources/PositionsResource.groovy
> +        if (!businessCenter?.trim()) {
Length checking against the businessCenter parameter should be done.

2017-07-25 21:36 UTC, adpextwindong commented on src/main/groovy/edu/oregonstate/mist/positions/core/Position.groovy
> +        new ResourceObject(
The self links are currently null/missing.

2017-07-25 21:36 UTC, adpextwindong commented on src/main/groovy/edu/oregonstate/mist/positions/resources/PositionsResource.groovy
> +    Response getPositions(@QueryParam('businessCenter') String businessCenter) {
The "type" query parameter should be added as a required parameter as it says in the Swagger. It should be checked for the value "student" as well.

2017-07-26 14:51 UTC, floppyears commented on src/main/groovy/edu/oregonstate/mist/positions/resources/PositionsResource.groovy
> +    Response getPositions(@QueryParam('businessCenter') String businessCenter) {
Agreed

2017-07-28 16:17 UTC, jaredkosanovic approved these changes

2017-07-28 16:46 UTC, merged